name: Backend CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
 Backend_Build_Test:
   stategies:
     matrix:
      python-versions: [3.12, 3.14]
     runs-on: ubuntu-latest
     steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-versions }} # Install Python
          cache: 'pip'

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt # Install dependencies
      
      - name: Lint Action
        working-directory: ./backend
        run: ruff check . # Check syntax errors

      - name: Run Tests
        working-directory: ./backend
        run: pytest # Run test

      - name: Build Section
        working-directory: ./backend
        run: python app.py # Builds project