name: Backend CI workflow
on:
  push:
    branches:
     - main 

  pull_request:
    branches:
     - main  
        
  workflow_dispatch:

jobs:
  Backend_Build_Test:
   strategy:
     matrix:
      python-versions: [3.12, 3.14]
   runs-on: ubuntu-latest
   services:
      database-container:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
   env:
     DATABASE_URL: postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@database-container:5432/${{ env.POSTGRES_DB }}
      
   steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }} # Install Python

      - name: Install dependencies
        working-directory: gym-management-system/backend
        run: pip install -r requirements.txt # Install dependencies
      
      - name: Install Ruff and pytest
        working-directory: gym-management-system/backend
        run: pip install ruff pytest # Install Ruff and pytest

      - name: Lint Action
        working-directory: gym-management-system/backend
        run: ruff check . --fix # Check syntax errors

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo 'waiting for postgres...'
            sleep 1
          done

      - name: Run Tests
        working-directory: gym-management-system/backend
        run: pytest # Run test