name: Backend CI workflow
on:
  push:
    branches:
     - main 

  pull_request:
    branches:
     - main  
        
  workflow_dispatch:

jobs:
  Backend_Build_Test:
   strategy:
     matrix:
      python-versions: [3.12, 3.14]
   runs-on: ubuntu-latest
   steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-versions }} # Install Python

      - name: Install dependencies
        working-directory: gym-management-system/backend
        run: pip install -r requirements.txt # Install dependencies
      
      - name: Install Ruff and pytest
        working-directory: gym-management-system/backend
        run: pip install ruff pytest # Install Ruff and pytest

      - name: Lint Action
        working-directory: gym-management-system/backend
        run: ruff check . --fix # Check syntax errors

      - name: Run Tests
        working-directory: gym-management-system/backend
        run: pytest # Run test