name: Deploy CI CD workflow
on:
    push:
      branches:
       - main

    pull_request:
      branches:
       - main
  
    workflow_dispatch:

jobs:
   Frontend_CI:
     uses: ./.github/workflows/Frontend_CI.yml

   Backend_CI:
     uses: ./.github/workflows/Backend_CI.yml

   Docker_Build_CI:  
     secrets: inherit
     needs:
      - Frontend_CI
      - Backend_CI

     uses: ./.github/workflows/Docker_Build_CI.yml
  
   Deploy_Application:
     needs: 
      - Docker_Build_CI
     runs-on: self-hosted
     steps:
       - name: Code checkout
         uses: actions/checkout@v4
            
       - name: Run Container
         run: |
           docker compose pull
           docker compose up -d