name: Deploy CI CD workflow
on:
    push:
      branches:
       - main

    pull_request:
      branches:
       - main
  
    workflow_dispatch:

jobs:
   Frontend CI:
     uses: ./.github/worklows/Frontend_CI.yml

   Backend CI:
     uses: ./.github/worklows/Backend_CI.yml

   Docker Build CI:  
     needs:
      - Frontend CI workflow
      - Backend CI workflow

     uses: ./.github/worklows/Docker_Build_CI.yml

  Deploy Application:
      runs-on: self-hosted
      steps:
          - name: Code checkout
            uses: actions/checkout@v4
            
          - name: Run Container
            run: |
             docker compose pull
             docker compose up -d