name: Deploy CI CD workflow
on:
   ## push:
   ##   branches:
   ##    - main

   ## pull_request:
   ##   branches:
   ##    - main
  
    workflow_dispatch:

jobs:
   Frontend_CI:
     uses: ./.github/workflows/Frontend_CI.yml

   Backend_CI:
     uses: ./.github/workflows/Backend_CI.yml

   Docker_Build_CI:  
     needs:
      - Frontend_CI
      - Backend_CI

     uses: ./.github/workflows/Docker_Build_CI.yml
     secrets: inherit

   Deploy_Application:
     needs: 
      - Docker_Build_CI
     runs-on: self-hosted
     steps:
       - name: Code checkout
         uses: actions/checkout@v4
            
       - name: Run Container
         working-directory: gym-management-system
         env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }} 
         run: |
           docker compose pull
           docker compose up -d

       - name: Run database migrations
         run: |
          docker exec gym-management-system-backend-container-1 \
          python -c "from config import app; from flask_migrate import upgrade; app.app_context().push(); upgrade(); print('DATABASE MIGRATION COMPLETED')"
          