name: Docker Build+Image_Scan+Push+Deploy CI workflow
on:
  ## push:
  ##  branches:
  ##    - main

  ## pull_request:
  ##  branches:
  ##    - main
  
 ## workflow_dispatch:

  ## workflow_run:
  ##  workflows:
  ##    - Frontend CI workflow
  ##    - Backend CI workflow
  ##  types:
  ##    - completed
    
  workflow_call:
    
jobs:
  Docker_Build_Image_Scan_Push_Deploy:
     ## strategy:
     ##   matrix:
     ##       image: ['${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-frontend:latest', '${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-backend:latest']
        
      runs-on: self-hosted
      steps:
        - name: Code Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

      ##  - name: Setup Docker
      ##    uses: docker/setup-docker-action@v4
      ##    with:
      ##      version: latest

        - name: Docker login # Docker login to DockerHub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Frontend Docker Build # Frontend Docker Build
          working-directory: gym-management-system/frontend
          run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-frontend:latest .
          
        - name: Backend Docker Build # Backend Docker Build
          working-directory: gym-management-system/backend
          run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-backend:latest .

        # Trivy - Frontend
        - name: Trivy Frontend Image Scan
          uses: aquasecurity/trivy-action@v0.36.0
          with:
               image-ref: '${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-frontend:latest'
               format: 'table'
               exit-code: '1'
               ignore-unfixed: true
               severity: 'CRITICAL,HIGH'

        # Trivy - Backend
        - name: Trivy Backend Image Scan
          uses: aquasecurity/trivy-action@v0.36.0
          with:
               image-ref: '${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-backend:latest'
               format: 'table'
               exit-code: '1'
               ignore-unfixed: true
               severity: 'CRITICAL,HIGH'

        - name: Push Frontend Docker Image  # Push Frontend Docker Image to DockerHub
          run: docker push ${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-frontend:latest

        - name: Push Backend Docker Image # Push Backend Docker Image to DockerHub
          run: docker push ${{ vars.DOCKERHUB_USERNAME }}/gym-management-system-backend:latest

        - name: Run Containers # Run Containers
          working-directory: gym-management-system
          env:
           DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }} 
          run: |
           docker compose pull
           docker compose up -d