name: Frontend CI workflow
on:
  push:
    branches:
     - main 

  pull_request:
    branches:
     - main  

  workflow_dispatch:

jobs:
  Frontend_Build_Test:
      runs-on: ubuntu-latest
      steps:
        - name: Source Code Checkout
          uses: actions/checkout@v4

        - name: Setup Node Js
          uses: actions/setup-node@v4
          with: 
            node-version: '24' #Install Latest Node.js
            
        - name: Install dependencies
          working-directory: gym-management-system/frontend
          run: |
           npm ci
           npm install --save-dev eslint jest eslint-plugin-jest --legacy-peer-deps # Install dependencies

        - name: ESLint Action
          working-directory: gym-management-system/frontend
          run: npm run lint --fix #Checks Syntax Errors

        - name: Run Tests
          working-directory: gym-management-system/frontend
          run: npm test #Run Test

        - name: Build Section
          working-directory: gym-management-system/frontend
          run: npm run build # Builds project