name: Frontend CI
on:
  push:
    branches:
     - main 

  pull_request:
    branches:
     - main  

  workflow_dispatch:

jobs:
   Frontend_Build_Test:
      runs-on: ubuntu-latest
      steps:
        - name: Source Code Checkout
          uses: actions/checkout@v4

        - name: Setup Node Js
          uses: actions/setup-node@v4
          with: 
            node-version: '20' #Install Latest Node.js
            
        - name: Install dependencies
          working-directory: ./frontend
          run: npm ci #Clean Install

        - name: ESLint Action
          working-directory: ./frontend
          run: npm run lint #Checks Syntax Errors

        - name: Run Tests
          working-directory: ./frontend
          run: npm test #Run Test

        - name: Build Section
          working-directory: ./frontend
          run: npm run build # Builds project