name: Secrets Scanning workflow
on:
    workflow_call:

jobs:
    secrets_scanning:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Run TruffleHog Action
              uses: trufflesecurity/trufflehog@v3.97.0
              with:
                extra_args: --results=verified,unknown